import javax.swing.*;
import java.util.*;
import java.text.*;
import java.util.logging.Level;
import java.util.logging.Logger;

public class InfoPanel  extends javax.swing.JPanel {

    /**
     * Creates new form MainPanel
     */
    public InfoPanel() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender_group = new javax.swing.ButtonGroup();
        FName = new javax.swing.JTextField();
        MI = new javax.swing.JTextField();
        LName = new javax.swing.JTextField();
        Label_FName = new javax.swing.JLabel();
        Label_MI = new javax.swing.JLabel();
        Label_LName = new javax.swing.JLabel();
        Label_DOB = new javax.swing.JLabel();
        DOB_Month = new javax.swing.JComboBox();
        DOB_Day = new javax.swing.JComboBox();
        DOB_Year = new javax.swing.JComboBox();
        Label_Gender = new javax.swing.JLabel();
        Gender_Male = new javax.swing.JRadioButton();
        Gener_Female = new javax.swing.JRadioButton();
        Label_Address1 = new javax.swing.JLabel();
        Address1 = new javax.swing.JTextField();
        Label_Address2 = new javax.swing.JLabel();
        Address2 = new javax.swing.JTextField();
        Label_City = new javax.swing.JLabel();
        City = new javax.swing.JTextField();
        Label_State = new javax.swing.JLabel();
        State = new javax.swing.JComboBox();
        Label_Zip = new javax.swing.JLabel();
        Zip = new javax.swing.JTextField();
        Label_Phone = new javax.swing.JLabel();
        Phone = new javax.swing.JTextField();
        Label_Email = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();

        setToolTipText("");

        Label_FName.setText("First Name");

        Label_MI.setText("MI");

        Label_LName.setText("Last Name");

        Label_DOB.setText("Date of Birth");

        DOB_Month.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        DOB_Month.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                DOB_MonthPropertyChange(evt);
            }
        });

        DOB_Day.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        DOB_Year.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950", "1949", "1948", "1947", "1946", "1945", "1944", "1943", "1942", "1941", "1940", "1939", "1938", "1937", "1936", "1935", "1934", "1933", "1932", "1931", "1930", "1929", "1928", "1927", "1926", "1925", "1924", "1923", "1922", "1921", "1920", "1919", "1918", "1917", "1916" }));
        DOB_Year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOB_YearActionPerformed(evt);
            }
        });

        Label_Gender.setText("Gender");

        gender_group.add(Gender_Male);
        Gender_Male.setText("Male");

        gender_group.add(Gener_Female);
        Gener_Female.setText("Female");

        Label_Address1.setText("Address 1");

        Label_Address2.setText("Address 2");

        Label_City.setText("City/Town");

        Label_State.setText("State");

        State.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming" }));

        Label_Zip.setText("Zip");

        Label_Phone.setText("Phone");

        Label_Email.setText("Email");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label_Zip)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Zip, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Label_Phone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Label_Email)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Email))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label_City)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(City, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Label_State)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(State, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Address2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(Label_FName)
                            .addGap(18, 18, 18)
                            .addComponent(FName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Label_MI)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(MI, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(16, 16, 16)
                            .addComponent(Label_LName)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(LName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Label_DOB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DOB_Month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DOB_Day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DOB_Year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Label_Gender))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Label_Address1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Address1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Label_Address2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Gender_Male)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Gener_Female)
                        .addGap(16, 16, 16)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(MI)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Label_MI)
                        .addComponent(FName)
                        .addComponent(Label_FName))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Label_LName)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_DOB)
                    .addComponent(DOB_Month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DOB_Day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DOB_Year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_Gender)
                    .addComponent(Gender_Male)
                    .addComponent(Gener_Female))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Address1)
                    .addComponent(Address1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_Address2)
                    .addComponent(Address2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_City)
                    .addComponent(Label_State)
                    .addComponent(City, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(State, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Zip)
                    .addComponent(Zip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_Phone)
                    .addComponent(Phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_Email)
                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DOB_MonthPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_DOB_MonthPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_DOB_MonthPropertyChange

    private void DOB_YearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOB_YearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOB_YearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address1;
    private javax.swing.JTextField Address2;
    private javax.swing.JTextField City;
    private javax.swing.JComboBox DOB_Day;
    private javax.swing.JComboBox DOB_Month;
    private javax.swing.JComboBox DOB_Year;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField FName;
    private javax.swing.JRadioButton Gender_Male;
    private javax.swing.JRadioButton Gener_Female;
    private javax.swing.JTextField LName;
    private javax.swing.JLabel Label_Address1;
    private javax.swing.JLabel Label_Address2;
    private javax.swing.JLabel Label_City;
    private javax.swing.JLabel Label_DOB;
    private javax.swing.JLabel Label_Email;
    private javax.swing.JLabel Label_FName;
    private javax.swing.JLabel Label_Gender;
    private javax.swing.JLabel Label_LName;
    private javax.swing.JLabel Label_MI;
    private javax.swing.JLabel Label_Phone;
    private javax.swing.JLabel Label_State;
    private javax.swing.JLabel Label_Zip;
    private javax.swing.JTextField MI;
    private javax.swing.JTextField Phone;
    private javax.swing.JComboBox State;
    private javax.swing.JTextField Zip;
    private javax.swing.ButtonGroup gender_group;
    // End of variables declaration//GEN-END:variables


    public JTextField getAddress1() {
        return Address1;
    }

    public void setAddress1(JTextField address1) {
        Address1 = address1;
    }

    public JTextField getAddress2() {
        return Address2;
    }

    public void setAddress2(JTextField address2) {
        Address2 = address2;
    }

    public JTextField getCity() {
        return City;
    }

    public void setCity(JTextField city) {
        City = city;
    }

    public JComboBox getDOB_Day() {
        return DOB_Day;
    }

    public void setDOB_Day(JComboBox DOB_Day) {
        this.DOB_Day = DOB_Day;
    }

    public JComboBox getDOB_Month() {
        return DOB_Month;
    }

    public void setDOB_Month(JComboBox DOB_Month) {
        this.DOB_Month = DOB_Month;
    }

    public JComboBox getDOB_Year() {
        return DOB_Year;
    }

    public void setDOB_Year(JComboBox DOB_Year) {
        this.DOB_Year = DOB_Year;
    }

    public JTextField getEmail() {
        return Email;
    }

    public void setEmail(JTextField email) {
        Email = email;
    }

    public JTextField getFName() {
        return FName;
    }

    public void setFName(JTextField FName) {
        this.FName = FName;
    }

    public JRadioButton getGender_Male() {
        return Gender_Male;
    }

    public void setGender_Male(JRadioButton gender_Male) {
        Gender_Male = gender_Male;
    }

    public JRadioButton getGener_Female() {
        return Gener_Female;
    }

    public void setGener_Female(JRadioButton gener_Female) {
        Gener_Female = gener_Female;
    }

    public JTextField getLName() {
        return LName;
    }

    public void setLName(JTextField LName) {
        this.LName = LName;
    }

    public JTextField getZip() {
        return Zip;
    }

    public void setZip(JTextField zip) {
        Zip = zip;
    }

    public JTextField getMI() {
        return MI;
    }

    public void setMI(JTextField MI) {
        this.MI = MI;
    }

    public JTextField getPhone() {
        return Phone;
    }

    public void setPhone(JTextField phone) {
        Phone = phone;
    }

    public JComboBox getState() {
        return State;
    }

    public void setState(JComboBox state) {
        State = state;
    }
    
    public boolean checkInfo() {
        String zip = Zip.getText();
        String phone = Phone.getText();
        String email = Email.getText();
        String dob = DOB_Month.getSelectedItem().toString() + "/" + DOB_Day.getSelectedItem().toString() + "/"
                + DOB_Year.getSelectedItem().toString();
        
        DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");
        //get current date time with Date()
        Date current_date = new Date();
        Date DOB = new Date();
        try {
            DOB = dateFormat.parse(dob);
        } catch (ParseException ex) {
            Logger.getLogger(InfoPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println(dateFormat.format(current_date));
        boolean status = false;
        int num = current_date.compareTo(DOB);
        System.out.println(num);
        if(num > 0) {
            if(zip.length() >= 5 && zip.length() <= 10)
            {
                if(phone.length() == 10) {
                    if(email.contains("@") && email.contains(".")){
                        status = true;
                    }
                }
            }
        }
        return status;
    }
    
}
